targets:
  $default:
    sources:
      exclude:
        - "lib/l10n/**"
    builders:
      isar_community_generator:isar_community_generator:
        generate_for:
          - lib/features/**/data/models/**.dart
