import 'dart:ui' as ui;

import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app.dart';
import 'core/config/telemetry_settings.dart';
import 'core/presentation/widgets/app_startup_widget.dart';
import 'core/providers/app_provider_observer.dart';
import 'core/utils/crash_reporter.dart';
import 'features/glucose/data/services/widget_sync_service.dart';
import 'firebase_options.dart';

/// Initializes Firebase with the project configuration generated by FlutterFire.
Future<void> initializeFirebaseIfEnabled() async {
  const enableFirebase = bool.fromEnvironment(
    'ENABLE_FIREBASE',
    defaultValue: true,
  );
  if (!enableFirebase) {
    return;
  }

  await TelemetrySettings.load();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await FirebaseAppCheck.instance.activate(
    providerAndroid: kDebugMode
        ? const AndroidDebugProvider()
        : const AndroidPlayIntegrityProvider(),
    providerApple: kDebugMode
        ? const AppleDebugProvider()
        : const AppleDeviceCheckProvider(),
  );
  final telemetryEnabled = TelemetrySettings.enabled;
  await FirebaseCrashlytics.instance.setCrashlyticsCollectionEnabled(
    telemetryEnabled,
  );
  await FirebaseAnalytics.instance.setAnalyticsCollectionEnabled(
    telemetryEnabled,
  );
  if (telemetryEnabled) {
    await FirebaseAnalytics.instance.logAppOpen();
  }
}

/// Main entrypoint function for the application.
///
/// Configures edge-to-edge system overlays, diagnostics error hooks, and launches
/// [AppStartupWidget] inside the root [ProviderScope] with [AppProviderObserver].
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Configure true edge-to-edge mode and transparent system overlays for modern devices.
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      systemNavigationBarColor: Colors.transparent,
    ),
  );

  FlutterError.onError = (FlutterErrorDetails details) {
    FlutterError.presentError(details);
    AppCrashReporter.recordError(
      details.exception,
      details.stack,
      reason: 'FlutterError: ${details.context?.toDescription()}',
      fatal: true,
    );
    if (TelemetrySettings.enabled) {
      FirebaseCrashlytics.instance.recordFlutterFatalError(details);
    }
  };

  ui.PlatformDispatcher.instance.onError = (Object error, StackTrace stack) {
    AppCrashReporter.recordError(
      error,
      stack,
      reason: 'Unhandled asynchronous platform error',
      fatal: true,
    );
    if (TelemetrySettings.enabled) {
      FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    }
    return true;
  };

  // Configures the shared App Group so native widgets can read Flutter data.
  await const WidgetSyncService().initialize();
  await initializeFirebaseIfEnabled();

  runApp(
    ProviderScope(
      observers: const [AppProviderObserver()],
      child: AppStartupWidget(onLoaded: (context) => const App()),
    ),
  );
}
